export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body>
        <header className="header">
          <h1 className="header__title">
            <span class="header__title__name">Caroline Gaillard</span>
            <span class="header__title__job">Kinésiologue</span>
          </h1>
        </header>
        {children}
        <footer className="footer"></footer>
      </body>
    </html>
  );
}
